### ISSUE TITLE
latest fastText / compile problems

### ISSUE THREAD

**Issue by dcsan** [vunb/node-fasttext#20]
I updated to latest fastText but there are problems with the compile step.
this is on OS-X

your previous version:
```
18 warnings generated.
  SOLINK_MODULE(target) Release/fasttext.node
  COPY /Users/dc/dev/rnd/node-fasttext-vunb/lib/binding/fasttext.node
  TOUCH Release/obj.target/action_after_build.stamp
```

latest version:
```
➜  node-fasttext git:(master) ✗ node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.1.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/fasttext/src/wrapper.o
../src/wrapper.cc:206:18: error: overload resolution selected deleted operator '='
    wordVectors_ = wordVectors;
    ~~~~~~~~~~~~ ^ ~~~~~~~~~~~
../src/../fastText/src/matrix.h:34:11: note: candidate function has been explicitly deleted
  Matrix& operator=(const Matrix&) = delete;
          ^
../src/wrapper.cc:264:12: error: no matching member function for call to 'getLine'
    dict_->getLine(in, words, labels, model_->rng);
    ~~~~~~~^~~~~~~
../src/../fastText/src/dictionary.h:101:13: note: candidate function not viable: requires 3 arguments, but 4 were provided
    int32_t getLine(std::istream&, std::vector<int32_t>&, std::vector<int32_t>&)
            ^
../src/../fastText/src/dictionary.h:103:13: note: candidate function not viable: requires 3 arguments, but 4 were provided
    int32_t getLine(std::istream&, std::vector<int32_t>&,
            ^
../src/wrapper.cc:275:13: error: no matching member function for call to 'predict'
    model_->predict(words, k, modelPredictions, hidden, output);
    ~~~~~~~~^~~~~~~
../src/../fastText/src/model.h:78:10: note: candidate function not viable: requires 4 arguments, but 5 were provided
    void predict(const std::vector<int32_t>&, int32_t, real,
         ^
../src/../fastText/src/model.h:75:10: note: candidate function not viable: requires 6 arguments, but 5 were provided
    void predict(const std::vector<int32_t>&, int32_t, real,
         ^
../src/wrapper.cc:299:21: error: no viable conversion from 'std::shared_ptr<Args>' to 'fasttext::Args'
    fastText_.train(a);
                    ^
../src/../fastText/src/args.h:22:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'std::shared_ptr<Args>' to 'fasttext::Args &&' for 1st argument
class Args {
      ^
../src/../fastText/src/args.h:22:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'std::shared_ptr<Args>' to 'const fasttext::Args &' for 1st argument
../src/../fastText/src/fasttext.h:113:24: note: passing argument to parameter here
  void train(const Args);
                       ^
../src/wrapper.cc:319:24: error: no viable conversion from 'std::shared_ptr<Args>' to 'fasttext::Args'
    fastText_.quantize(a);
                       ^
../src/../fastText/src/args.h:22:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'std::shared_ptr<Args>' to 'fasttext::Args &&' for 1st argument
class Args {
      ^
../src/../fastText/src/args.h:22:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'std::shared_ptr<Args>' to 'const fasttext::Args &' for 1st argument
../src/../fastText/src/fasttext.h:95:27: note: passing argument to parameter here
  void quantize(const Args);
                          ^
5 errors generated.
make: *** [Release/obj.target/fasttext/src/wrapper.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/dc/.config/yarn/global/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/dc/.config/yarn/global/node_modules/.bin/node-gyp" "build"
gyp ERR! cwd /Users/dc/dev/rnd/node-fasttext
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by dcsan** [comment]
however with simple make it compiles fine.

```
➜  fastText git:(master) make clean && make
rm -rf *.o fasttext
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/args.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/dictionary.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/productquantizer.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/matrix.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/qmatrix.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/vector.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/model.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/utils.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/fasttext.cc
c++ -pthread -std=c++0x -march=native -O3 -funroll-loops args.o dictionary.o productquantizer.o matrix.o qmatrix.o vector.o model.o utils.o fasttext.o src/main.cc -o fasttext
➜  fastText git:(master)
```

I don't know much about node-gyp, how to control the build compiler more tightly?

**Comment by dcsan** [comment]
so I looked at the exact command line used in the normal compile step:

    c++ -pthread -std=c++0x -march=native -O3 -funroll-loops -c src/args.cc

and also in the Makefile

```make
CXX = c++
CXXFLAGS = -pthread -std=c++0x -march=native
OBJS = args.o dictionary.o productquantizer.o matrix.o qmatrix.o vector.o model.o utils.o fasttext.o
INCLUDES = -I.
```

and tried to add those as flags to the XCODE args in the `binding.gyp` file

```

          [ "OS=='mac'", {
              "cflags+": [ "-stdlib=libc++" ],
              "xcode_settings": {
                  "OTHER_CPLUSPLUSFLAGS" : [ 
                    "-std=c++0x", 
                    "-stdlib=libc++", 
                    "-march=native",
                    "-O3",
                    "-funroll-loops",
                    "-c",
                    "-pthread" ],
                  "OTHER_LDFLAGS": [ 
                    "-stdlib=libc++"
                  ],
                  "GCC_ENABLE_CPP_EXCEPTIONS": "YES",
                  "MACOSX_DEPLOYMENT_TARGET": "10.7",
                  "CLANG_CXX_LANGUAGE_STANDARD":"c++0x",
                  "CLANG_CXX_LIBRARY": "libc++"
              },
          }],
```

but still get the same compile errors.

**Comment by dcsan** [comment]
```
  CXX(target) Release/obj.target/fasttext/src/wrapper.o
../src/wrapper.cc:206:18: error: overload resolution selected deleted operator '='
    wordVectors_ = wordVectors;
    ~~~~~~~~~~~~ ^ ~~~~~~~~~~~
../src/../fastText/src/matrix.h:34:11: note: candidate function has been explicitly deleted
  Matrix& operator=(const Matrix&) = delete;
          ^
../src/wrapper.cc:264:12: error: no matching member function for call to 'getLine'
    dict_->getLine(in, words, labels, model_->rng);
    ~~~~~~~^~~~~~~
../src/../fastText/src/dictionary.h:101:13: note: candidate function not viable: requires 3 arguments, but 4 were provided
    int32_t getLine(std::istream&, std::vector<int32_t>&, std::vector<int32_t>&)
            ^
../src/../fastText/src/dictionary.h:103:13: note: candidate function not viable: requires 3 arguments, but 4 were provided
    int32_t getLine(std::istream&, std::vector<int32_t>&,
            ^
../src/wrapper.cc:275:13: error: no matching member function for call to 'predict'
    model_->predict(words, k, modelPredictions, hidden, output);
```

some of these maybe down to compiler option flags, but I am confused how there would be mismatches like this unless headers are somehow not getting noticed...

```
../src/wrapper.cc:275:13: error: no matching member function for call to 'predict'
    model_->predict(words, k, modelPredictions, hidden, output);
```

**Comment by vunb** [comment]
Hi @dcsan 

The main reason as i know that is the fastText has many changes in their api(s). For instances:

* The number of arguments are added
* The order of the argument changes
* Some others ...

We might investigate the changes to make it works correctly.

**Comment by dcsan** [comment]
indeed, but why that it compiles correctly with plain `make` and not from `node-gyp` ?

I noticed another way to compile a native module, like this one

https://github.com/Planeshifter/node-word2vec

maybe worth trying that method and avoiding node-gyp altogether?

"postinstall": "make --directory=src",

**Comment by vunb** [comment]
That is not problem of either `make` or `node-gyp`. It occurs in our binding `C++` code, namely `wrapper.cc` does not use and parse arguments correctly.

```bash
../src/wrapper.cc:275:13: error: no matching member function for call to 'predict'
    model_->predict(words, k, modelPredictions, hidden, output);
```

So, we need to change and clean up the binding code a little is okay!

> I noticed another way to compile a native module, like this one
>
> https://github.com/Planeshifter/node-word2vec
> 
> maybe worth trying that method and avoiding node-gyp altogether?

There are many ways to build C++ code to binding the original code:

* [worker subprocess](https://nikhilm.github.io/uvbook/processes.html) runs on top of [libuv](https://libuv.org/)
* or use [N-API](https://nodejs.org/api/n-api.html) which available and stable in this Octorber, [abi-stable-node](https://github.com/nodejs/abi-stable-node)

For now i think we might try to make it works and wait a bit time to use **N-API** and make it has well performance.

**Comment by dcsan** [comment]
ohhh... I didn't realize you had written those wrapper functions. now I understand... so those provide a gateway to V8, effectively adding more native methods to node?

Let me know if I can help dig into solving this, but I would need some guidance from you as to where to look...

**Comment by vunb** [comment]
Okay.

Basically we have four main groups of files:

1. addon.cc defines and separates two main features: `Query` and `Classifier`
2. Fasttext api binding definition:
  * `query.h` - binding to fastText Word representations
  * `classifier.h` - binding to fastText Text classification
3. Wrapper class
  * Binding and linking to original of fasttext api source
  * Add constraints and validation to models info and some others.
  * Ex: `wrapper.h`, `wrapper.cc`
4. Support classes
  * Each function will separate to a class which bind functions between `NodeJS` and `Wrapper` class.
  * Execute task and handle errors
  * Ex: `train.h`, `train.cc`, ...

I hope the above infos give you understand and have clarification. If you have any confusion, please let me know!

**Comment by ao** [comment]
This appears because it is trying to download files such as:
`https://github.com/vunb/node-fasttext/releases/download/0.2.3/fasttext-v0.2.3-node-v64-darwin-x64.tar.gz`

Where the `v64` should be a `v46`.

![image](https://user-images.githubusercontent.com/1898708/54203027-421fb400-44c9-11e9-903d-1efd256d06f8.png)

**Comment by vunb** [comment]
@ao sorry for late reply! I am working on branch **n-api** which is trying to convert the source code to use [N-API](https://nodejs.org/api/n-api.html), a new ABI-stable Node.js API for native modules (instead of **nan** before). When the implementation is ready and works correctly then i will release the new version of this package. It means the package will not worry about any Node version you use, which is greater than `8.0.0`.
